language: go

go:
    - "1.9"
    - "1.10"

install:
  - make install-linters

script:
  # The awk pipe removes duplicate lines from the log output, there can be many of them
  - make PARALLEL="-parallel=1" MIN_SHUTDOWN_WAIT="-min-shutdown-wait=12s" check | cut -d " " -f 2- | awk '!a[$0]++'
